version: '3.4'
services:
  postgres:
    restart: always
    image: 'postgres:12.2'
    environment:
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_IN_PORT}:${POSTGRES_OUT_PORT}
    expose:
      - ${POSTGRES_IN_PORT}
    volumes:
      - /var/lib/postgresql/docker/database:/var/lib/postgresql/database
  app:
    build: .
    env_file:
      - .env
    environment:
        SPRING_PROFILES_ACTIVE: prod
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
        SPRING_DATASOURCE_USERNAME: ${USER_NAME}
        SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
    expose:
      - ${SERVER_PORT}
    depends_on:
      - postgres
  nginx_server:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
volumes:
  database: