version: '3.4'
services:
  postgres:
    restart: always
    image: 'postgres:12.2'
    environment:
      POSTGRES_USER: roharon
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gmoney-test
    ports:
      - 25432:5432
    volumes:
      - /var/lib/postgresql/docker/database:/var/lib/postgresql/database
    networks:
      - gmoney_local_network
  app:
    build: .
    env_file:
      - .env
    environment:
        SPRING_PROFILES_ACTIVE: develop
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/gmoney-test
        SPRING_DATASOURCE_USERNAME: roharon
        SPRING_DATASOURCE_PASSWORD: password
        SERVER_PORT: 8055
    ports:
      - 8055:8055
    networks:
      - nginx_network
      - gmoney_local_network
    depends_on:
      - postgres
  nginx_server:
    image: nginx
    restart: "on-failure"
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - nginx_network
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  nginx_network:
    external: true
  gmoney_local_network: