spring:
  datasource:
    username: roharon
    password: password
    url: jdbc:postgresql://localhost:25432/gmoney-test
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
server:
  port: 8055