spring:
  datasource:
    username: ${USER_NAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:${POSTGRES_IN_PORT}/gmoney
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT}
