spring:
  profiles: default
  datasource:
    username: roharon
    password: password
    url: jdbc:postgresql://localhost:5432/gmoney
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
