# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Docker compose CI & CD

on:
  push:
    branches: [ master ]

jobs:
  gradle_build:
    name: Gradle Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  docker_build_and_push:
    name: Docker Build & Push to registry
    needs: gradle_build
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_IN_PORT: ${{ secrets.POSTGRES_IN_PORT }}
      POSTGRES_OUT_PORT: ${{ secrets.POSTGRES_OUT_PORT }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

    steps:
    - uses: azure/docker-login@v1
      name: Login to Docker Registry
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_URL }} # default: index.docker.io
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: |
        docker network create nginx_network
        docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check Logs
      run: docker logs app
    - uses: docker/build-push-action@v1
      name: Docker build & Push to Registry
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        repository: ${{ secrets.DOCKER_REGISTRY_USERNAME}}/gmoney-store-server
        tag_with_ref: true
        tag_with_sha: true
